openapi: 3.0.1
info:
  title: Custom Pod Autoscaler
  description: "Custom Pod Autoscaler API; for querying metrics and evaluations of scaling."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: metric
  description: Metric for scaling
- name: evaluation
  description: Evaluation decision for scaling
paths:
  /metrics:
    get:
      tags:
      - metric
      summary: Get metrics for CPA
      operationId: getMetrics
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceMetric"
        default:
          description: Error
  /evaluation:
    get:
      tags:
      - evaluation
      summary: Get evaluation decision for CPA
      operationId: getEvaluation
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Evaluation"
        default:
          description: Error
components:
  schemas:
    ResourceMetric:
      required:
      - deployment
      - metrics
      type: object
      properties:
        deployment:
          type: string
          example: example-deployment
        metrics:
          type: array
          items:
            $ref: "#/components/schemas/Metric"
    Evaluation:
      required:
      - target_replicas
      type: object
      properties:
        target_replicas:
          type: integer
          example: 2
    Metric:
      required:
      - pod
      - value
      type: object
      properties:
        pod:
          type: string
          example: example-pod
        value:
          type: string
          example: value
