apiVersion: custompodautoscaler.com/v1alpha1
kind: CustomPodAutoscaler
metadata:
  name: player-count-scaler
spec:
  image: example-python-custom-pod-autoscaler:latest
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-metric
  config: 
    - name: interval
      value: "5000"
