apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-metric
  labels:
    app: flask-metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-metric
  template:
    metadata:
      labels:
        app: flask-metric
    spec:
      containers:
      - name: flask-metric
        image: eu.gcr.io/custom-pod-autoscaler-demo/flask-metric:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
