evaluate:
  type: "shell"
  timeout: 2500
  shell: 
    entrypoint: "python"
    command: 
      - "/evaluate.py"
metric:
  type: "http"
  timeout: 2500
  http:
    method: "GET"
    url: "https://www.random.org/integers/?num=1&min=1&max=5&col=1&base=10&format=plain&rnd=new"
    successCodes:
      - 200
    parameterMode: query
minReplicas: 0
runMode: "per-resource"
