apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: simple-pod-metrics-golang
spec:
  template:
    spec:
      containers:
      - name: simple-pod-metrics-golang
        image: simple-pod-metrics-golang:latest
        imagePullPolicy: Always
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-metric
  config: 
    - name: interval
      value: "10000"
