apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: argo-rollouts
spec:
  template:
    spec:
      containers:
      - name: argo-rollouts
        image: argo-rollouts:latest
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rollouts-demo
  roleRequiresArgoRollouts: true
  config:
    - name: interval
      value: "10000"
