apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: zero-scaler
spec:
  template:
    spec:
      containers:
      - name: zero-scaler
        image: zero-scaler:latest
        imagePullPolicy: Always
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-kubernetes
  config: 
    - name: interval
      value: "10000"
