evaluate:
  type: "shell"
  timeout: 2500
  shell: 
    entrypoint: "python"
    command: "/evaluate.py"
metric:
  type: "shell"
  timeout: 2500
  shell: 
    entrypoint: "python"
    command: "/evaluate.py"
runMode: "per-resource"