/*
Copyright 2021 The Custom Pod Autoscaler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package k8smetric provides the definitions for data generated by the Kubernetes Metric Gathering functionality
package k8smetric

import (
	"github.com/jthomperoo/custom-pod-autoscaler/config"
	"github.com/jthomperoo/custom-pod-autoscaler/k8smetric/external"
	"github.com/jthomperoo/custom-pod-autoscaler/k8smetric/object"
	"github.com/jthomperoo/custom-pod-autoscaler/k8smetric/pods"
	"github.com/jthomperoo/custom-pod-autoscaler/k8smetric/resource"
)

// Metric is a metric that has been retrieved from the K8s metrics server
type Metric struct {
	CurrentReplicas int32                `json:"current_replicas"`
	Spec            config.K8sMetricSpec `json:"spec"`
	Resource        *resource.Metric     `json:"resource,omitempty"`
	Pods            *pods.Metric         `json:"pods,omitempty"`
	Object          *object.Metric       `json:"object,omitempty"`
	External        *external.Metric     `json:"external,omitempty"`
}
